apiVersion: v1
kind: Service
metadata: 
  labels: 
    name: cassandra
  name: cassandra
spec: 
  ports:
  - name: cql
    port: 9042
    targetPort: 9042
  - name: thrift
    port: 9160
    targetPort: 9160
  selector: 
    name: cv
