apiVersion: v1
kind: Pod
metadata:
  labels:
    name: cv
  name: cv
spec:
  containers:
  - image: %%docker-private-registry%%/cv_cassandra
    name: cassandra
    ports:
    - name: cql
      containerPort: 9042
    - name: thrift
      containerPort: 9160
    volumeMounts:
    - name: data
      mountPath: /cassandra_data
    env:
    - name: MAX_HEAP_SIZE
      value: 512M
    - name: HEAP_NEWSIZE
      value: 100M
    - name: KUBERNETES_API_PROTOCOL
      value: http
  - image: %%docker-private-registry%%/cv_spark
    args:
    - /start-worker.sh
    name: spark-worker
    ports:
    - name: spark-workerui
      containerPort: 8888
    - name: spark-w-webui
      containerPort: 8081
  volumes:
    - name: data
      emptyDir: {}

    
