kind: Service
apiVersion: v1
metadata:
  labels:
    name: spark-master
  name: spark-master
spec:
  ports:
    - name: spark-master
      port: 7077
      targetPort: 7077
    - name: spark-m-webui
      port: 8080
      targetPort: 8080
    - name: spark-app
      port: 4040
      targetPort: 4040
  selector:
    name: spark-master
