kind: Service
apiVersion: v1beta3
metadata:
  labels:
    name: spark-master
  name: spark-master
spec:
  ports:
    - name: spark-master
      port: 7077
      targetPort: 7077
    - name: spark-master-webui
      port: 8080
      targetPort: 8080
  selector:
    name: spark-master
