apiVersion: v1
kind: Pod
metadata:
  labels:
    name: spark-master
  name: spark-master
spec:
  containers:
  - name: spark-master
    resources:
      limits:
        cpu: "1"
    image: %%docker-private-registry%%/cv_spark
    args:
      - /start-master.sh
    ports:
    - name: spark-master
      containerPort: 7077
    - name: spark-m-webui
      containerPort: 8080
    - name: spark-app
      containerPort: 4040
