apiVersion: v1
kind: Pod
metadata:
  labels:
    name: docker-private-registry
  name: docker-private-registry
spec:
  containers:
  - name: docker-private-registry
    image: registry
    ports:
    - name: docker-reg
      hostPort: 5000  
      containerPort: 5000
