kind: Service
apiVersion: v1beta3
metadata:
  labels:
    name: docker-private-registry
  name: docker-private-registry
spec:
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    name: docker-private-registry
