apiVersion: v1beta3
kind: Pod
metadata:
  name: gpg-adminbox
  labels:
    name: gpg-adminbox
spec:
  containers:
  - name: gpg-adminbox
    resources:
      limits:
        cpu: "1"      
    image: pwais/hack # TODO: gpg account
    privileged: true
    ports:
    - name: ssh
      containerPort: 22
      hostPort: 10022
      protocol: tcp
    # A fix to run docker (daemon) in docker: -v /dev:/dev
    # But we just run using the host's docker: -v /var/run/docker.sock:/var/run/docker.sock
    volumeMounts:
      - name: dockersock
        mountPath: /var/run/docker.sock
  volumes:
    - name: dockersock
      hostPath:
        path: /var/run/docker.sock
